-- MySQL Script generated by MySQL RAJABU KITINDI
-- Nov 2019
-- Model: New Model Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pb_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pb_db` ;

-- -----------------------------------------------------
-- Schema pb_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pb_db` DEFAULT CHARACTER SET utf8 ;
USE `pb_db` ;



-- -----------------------------------------------------
-- HR MODULE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `pb_db`.`EmploymentType_HR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`EmploymentType_HR` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`Employmentype_HR` (
 `EmpTypeId` INT NOT NULL AUTO_INCREMENT,
 `EmploymentType` VARCHAR(255) NOT NULL,
 `Description` VARCHAR(255),
 PRIMARY KEY (`EmpTypeId`));

-- -----------------------------------------------------
-- Table `pb_db`.`PaymentType_HR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`PaymentType_HR` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`PaymentType_HR` (
 `PayTypeId` INT NOT NULL AUTO_INCREMENT,
 `PaymentType` VARCHAR(255) NOT NULL,
 `Description` VARCHAR(255),
 PRIMARY KEY (`PayTypeId`));

-- -----------------------------------------------------
-- Table `pb_db`.`PaymentSchedule_HR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`PaymentSchedule_HR` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`PaymentSchedule_HR` (
 `PayScheduleId` INT NOT NULL AUTO_INCREMENT,
 `PaymentSchedule` VARCHAR(255) NOT NULL,
 `Description` VARCHAR(255),
 PRIMARY KEY (`PayScheduleId`));

-- -----------------------------------------------------
-- Table `pb_db`.`LeaveType_HR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`LeaveType_HR` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`LeaveType_HR` (
 `LeaveTypeId` INT NOT NULL AUTO_INCREMENT,
 `LeaveType` VARCHAR(255) NOT NULL,
 `PaymentStatus` VARCHAR(255) NOT NULL,
 `Description` VARCHAR(255),
 PRIMARY KEY (`LeaveTypeId`));

-- -----------------------------------------------------
-- Table `pb_db`.`PersonalInfo_HR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`PersonalInfo_HR` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`PersonalInfo_HR` (
 `EmployeeId` VARCHAR(255) NOT NULL,
 `FirstNames` VARCHAR(255) NOT NULL,
 `LastNames` VARCHAR(255) NOT NULL,
 `JoiningDate` DATETIME NOT NULL,
 `Department` VARCHAR(255) NOT NULL,
 `PositionTittle` VARCHAR(255) NOT NULL,
 `Gender` VARCHAR(255) NOT NULL,
 `DateofBirth` DATETIME NOT NULL,
 `EmpTypeId` INT NOT NULL,
 PRIMARY KEY (`EmployeeId`), 
 INDEX `EmpTypeId_idx` (`EmpTypeId` ASC), 
 CONSTRAINT `EmpTypeId`
 FOREIGN KEY (`EmpTypeId`)
 REFERENCES `pb_db`.`EmploymentType_HR` (`EmpTypeId`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT);

-- -----------------------------------------------------
-- Table `pb_db`.`SalaryInfo_HR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`SalaryInfo_HR`;

CREATE TABLE IF NOT EXISTS `pb_db`.`SalaryInfo_HR` (
 `SalInfoId` INT NOT NULL AUTO_INCREMENT,
 `EmployeeId` VARCHAR(255) NOT NULL,
 `BaseSalary` INT NOT NULL,
 `StateTax` INT NOT NULL,
 `FederalTax` INT NOT NULL,
 `SocialSec` INT NOT NULL,
 `NetIncome` INT NOT NULL,
 `PayScheduleId` INT NOT NULL,
 PRIMARY KEY (`SalInfoId`), 
 INDEX `EmployeeId_idx` (`EmployeeId` ASC), 
 INDEX `PayScheduleId_idx` (`PayScheduleId` ASC),
 CONSTRAINT `EmployeeId_SI`
 FOREIGN KEY (`EmployeeId`)
 REFERENCES `pb_db`.`PersonalInfo_HR` (`EmployeeId`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT,
 CONSTRAINT `PayScheduleId`
 FOREIGN KEY (`PayScheduleId`)
 REFERENCES `pb_db`.`PaymentSchedule_HR` (`PayScheduleId`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT);

-- -----------------------------------------------------
-- Table `pb_db`.`LeaveInfo_HR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`LeaveInfo_HR`;

CREATE TABLE IF NOT EXISTS `pb_db`.`LeaveInfo_HR` (
 `LeaveInfoId` INT NOT NULL AUTO_INCREMENT,
 `EmployeeId` VARCHAR(255) NOT NULL,
 `LeaveTypeId` INT NOT NULL,
 `NumberofDays` INT NOT NULL,
 `StartDate` DATETIME NOT NULL,
 `EndDate` DATETIME NOT NULL,
 PRIMARY KEY (`LeaveInfoId`), 
 INDEX `EmployeeId_idx` (`EmployeeId` ASC), 
 INDEX `LeaveTypeId_idx` (`LeaveTypeId` ASC),
 CONSTRAINT `EmployeeId_LI`
 FOREIGN KEY (`EmployeeId`)
 REFERENCES `pb_db`.`PersonalInfo_HR` (`EmployeeId`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT,
 CONSTRAINT `LeaveTypeId`
 FOREIGN KEY (`LeaveTypeId`)
 REFERENCES `pb_db`.`LeaveType_HR` (`LeaveTypeId`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT);

-- -----------------------------------------------------
-- Table `pb_db`.`BankInfo_HR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`BankInfo_HR` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`BankInfo_HR` (
 `BankInfoId` INT NOT NULL AUTO_INCREMENT,
 `EmployeeId` VARCHAR(255) NOT NULL,
 `BankName` VARCHAR(255) NOT NULL,
 `BankCode` VARCHAR(255) NOT NULL,
 `BranchCodeNumber` VARCHAR(255) NOT NULL,
 `AccountNumber` INT NOT NULL,
 `CLABE` INT NOT NULL,
 `AccountType` VARCHAR(255) NOT NULL,
 PRIMARY KEY (`BankInfoId`), 
 INDEX `EmployeeId_idx` (`EmployeeId` ASC), 
 CONSTRAINT `EmployeeId_BI`
 FOREIGN KEY (`EmployeeId`)
 REFERENCES `pb_db`.`PersonalInfo_HR` (`EmployeeId`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT);



-- -----------------------------------------------------
-- PRODUCTION MODULE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `pb_db`.`SupplierCategory_PROD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`SupplierCategory_PROD` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`SupplierCategory_PROD` (
 `CategoryId` INT NOT NULL AUTO_INCREMENT,
 `CategoryName` VARCHAR(255) NOT NULL,
 `Description` VARCHAR(255),
 PRIMARY KEY (`CategoryId`));

-- -----------------------------------------------------
-- Table `pb_db`.`SupplierInfo_PROD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`SupplierInfo_PROD` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`SupplierInfo_PROD` (
 `SupplierId` VARCHAR(255) NOT NULL,
 `BusinessName` VARCHAR(255) NOT NULL,
 `ContactName` VARCHAR(255) NOT NULL,
 `Address` VARCHAR(255) NOT NULL,
 `EmailAddress` VARCHAR(255) NOT NULL,
 `PhoneNumber` INT NOT NULL,
 `CategoryId` INT NOT NULL,
 PRIMARY KEY (`SupplierId`), 
 INDEX `CategoryId_idx` (`CategoryId` ASC), 
 CONSTRAINT `CategoryId`
 FOREIGN KEY (`CategoryId`)
 REFERENCES `pb_db`.`SupplierCategory_PROD` (`CategoryId`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT);
 
 -- -----------------------------------------------------
-- Table `pb_db`.`FarmInfo_PROD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`FarmInfo_PROD` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`FarmInfo_PROD` (
 `FarmId` INT NOT NULL AUTO_INCREMENT,
 `FarmName` VARCHAR(255) NOT NULL,
 `SupplierId` VARCHAR(255) NOT NULL,
 PRIMARY KEY (`FarmId`), 
 INDEX `SupplierId_idx` (`SupplierId` ASC), 
 CONSTRAINT `SupplierId_FI`
 FOREIGN KEY (`SupplierId`)
 REFERENCES `pb_db`.`SupplierInfo_PROD` (`SupplierId`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT);
 
 -- -----------------------------------------------------
-- Table `pb_db`.`TruckInfo_PROD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`TruckInfo_PROD` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`TruckInfo_PROD` (
 `RegNumber` VARCHAR(255) NOT NULL,
 `Make` VARCHAR(255) NOT NULL,
 `Model` VARCHAR(255) NOT NULL,
 `Capacity` VARCHAR(255) NOT NULL,
 `DriverName` VARCHAR(255) NOT NULL,
 `SupplierId` VARCHAR(255) NOT NULL,
 PRIMARY KEY (`RegNumber`), 
 INDEX `SupplierId_idx` (`SupplierId` ASC), 
 CONSTRAINT `SupplierId_TI`
 FOREIGN KEY (`SupplierId`)
 REFERENCES `pb_db`.`SupplierInfo_PROD` (`SupplierId`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT);
 
-- -----------------------------------------------------
-- Table `pb_db`.`ProductInfo_PROD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`ProductInfo_PROD` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`ProductInfo_PROD` (
 `ProductCode` VARCHAR(255) NOT NULL,
 `BrandName` VARCHAR(255) NOT NULL,
 `Quality` VARCHAR(255) NOT NULL,
 `ProductPhoto` BLOB NOT NULL,
 `SellingPrice` INT NOT NULL,
 `SupplierId` VARCHAR(255) NOT NULL,
 PRIMARY KEY (`ProductCode`), 
 INDEX `SupplierId_idx` (`SupplierId` ASC), 
 CONSTRAINT `SupplierId_PI`
 FOREIGN KEY (`SupplierId`)
 REFERENCES `pb_db`.`SupplierInfo_PROD` (`SupplierId`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT);

-- -----------------------------------------------------
-- Table `pb_db`.`CaseDetails_PROD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`CaseDetails_PROD` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`CaseDetails_PROD` (
 `CaseCode` VARCHAR(255) NOT NULL,
 `CaseName` VARCHAR(255) NOT NULL,
 `BrandName` VARCHAR(255) NOT NULL,
 `CasePhoto` BLOB NOT NULL,
 `PurchasePrice` INT NOT NULL,
 `SupplierId` VARCHAR(255) NOT NULL,
 PRIMARY KEY (`CaseCode`), 
 INDEX `SupplierId_idx` (`SupplierId` ASC), 
 CONSTRAINT `SupplierId_CD`
 FOREIGN KEY (`SupplierId`)
 REFERENCES `pb_db`.`SupplierInfo_PROD` (`SupplierId`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT);




-- -----------------------------------------------------
-- SALES MODULE
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Table `pb_db`.`POSInfo_SAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`POSInfo_SAL` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`POSInfo_SAL` (
 `POSId` INT NOT NULL AUTO_INCREMENT,
 `POSName` VARCHAR(255) NOT NULL,
 `EmployeeID` VARCHAR(255),
 PRIMARY KEY (`POSId`),
 INDEX `EmployeeID_idx` (`EmployeeID` ASC), 
 CONSTRAINT `EmployeeID_POSI`
 FOREIGN KEY (`EmployeeID`)
 REFERENCES `pb_db`.`PersonalInfo_HR` (`EmployeeID`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT);




-- -----------------------------------------------------
-- ACCOUNTING MODULE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `pb_db`.`BatchDetails_ACC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`BatchDetails_ACC` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`BatchDetails_ACC` (
 `ControlNumber` VARCHAR(255) NOT NULL,
 `SupplierId` VARCHAR(255) NOT NULL,
 `RegNumber` VARCHAR(255) NOT NULL,
 `DateDispatched` DATETIME NOT NULL,
 `DateArrived` DATETIME NOT NULL,
 `BatchDocument` BLOB NOT NULL,
 PRIMARY KEY (`ControlNumber`), 
 INDEX `SupplierId_idx` (`SupplierId` ASC), 
 INDEX `RegNumber_idx` (`RegNumber` ASC),
 CONSTRAINT `SupplierId_BD`
 FOREIGN KEY (`SupplierId`)
 REFERENCES `pb_db`.`SupplierInfo_PROD` (`SupplierId`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT,
 CONSTRAINT `RegNumber_BD`
 FOREIGN KEY (`RegNumber`)
 REFERENCES `pb_db`.`TruckInfo_PROD` (`RegNumber`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT);

-- -----------------------------------------------------
-- Table `pb_db`.`ReceiveProduct_ACC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`ReceiveProduct_ACC` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`ReceiveProduct_ACC` (
 `ProductReceiptNumber` INT NOT NULL AUTO_INCREMENT,
 `ProductCode` VARCHAR(255) NOT NULL,
 `ControlNumber` VARCHAR(255) NOT NULL,
 `FarmId` INT NOT NULL,
 `Quantity` INT NOT NULL,
 `CaseCode` VARCHAR(255) NOT NULL,
 `DateReceived` DATETIME NOT NULL,
 PRIMARY KEY (`ProductReceiptNumber`), 
 INDEX `ProductCode_idx` (`ProductCode` ASC), 
 INDEX `ControlNumber_idx` (`ControlNumber` ASC),
 INDEX `FarmId_idx` (`FarmId` ASC),
 INDEX `CaseCode_idx` (`CaseCode` ASC),
 CONSTRAINT `ProductCode_RP`
 FOREIGN KEY (`ProductCode`)
 REFERENCES `pb_db`.`ProductInfo_PROD` (`ProductCode`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT,
 CONSTRAINT `ControlNumber_RP`
 FOREIGN KEY (`ControlNumber`)
 REFERENCES `pb_db`.`BatchDetails_ACC` (`ControlNumber`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT,
 CONSTRAINT `FarmId_RP`
 FOREIGN KEY (`FarmId`)
 REFERENCES `pb_db`.`FarmInfo_PROD` (`FarmId`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT,
 CONSTRAINT `CaseCode_RP`
 FOREIGN KEY (`CaseCode`)
 REFERENCES `pb_db`.`CaseDetails_PROD` (`CaseCode`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT);

-- -----------------------------------------------------
-- Table `pb_db`.`DispatchProduct_ACC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`DispatchProduct_ACC` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`DispatchProduct_ACC` (
 `DispatchRefNum` INT NOT NULL AUTO_INCREMENT,
 `ProductReceiptNumber` INT NOT NULL,
 `POSId` INT NOT NULL,
 `Quantity` INT NOT NULL,
 `DateDispatched` DATETIME NOT NULL,
 `Dispatched` INT NOT NULL,
 `Comments` VARCHAR(255),
 PRIMARY KEY (`DispatchRefNum`), 
 INDEX `ProductReceiptNumber_idx` (`ProductReceiptNumber` ASC), 
 INDEX `POSId_idx` (`POSId` ASC),
 CONSTRAINT `ProductReceiptNumber_DP`
 FOREIGN KEY (`ProductReceiptNumber`)
 REFERENCES `pb_db`.`ReceiveProduct_ACC` (`ProductReceiptNumber`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT,
 CONSTRAINT `POSId_DP`
 FOREIGN KEY (`POSId`)
 REFERENCES `pb_db`.`POSInfo_SAL` (`POSId`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT);

-- -----------------------------------------------------
-- Table `pb_db`.`BatchExp_ACC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`BatchExp_ACC` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`BatchExp_ACC` (
 `BatchExpId` INT NOT NULL AUTO_INCREMENT,
 `ControlNumber` VARCHAR(255) NOT NULL,
 `FreighCost` INT NOT NULL,
 `iva` INT NOT NULL,
 `retiva` INT NOT NULL,
 PRIMARY KEY (`BatchExpId`),
 INDEX `ControlNumber_idx` (`ControlNumber` ASC), 
 CONSTRAINT `ControlNumber_BC`
 FOREIGN KEY (`ControlNumber`)
 REFERENCES `pb_db`.`BatchDetails_ACC` (`ControlNumber`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT);
 
 
 
 
-- -----------------------------------------------------
-- SALES MODULE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `pb_db`.`POSExpTypes_SAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`POSExpTypes_SAL` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`POSExpTypes_SAL` (
 `POSExpTypeId` INT NOT NULL AUTO_INCREMENT,
 `POSExpType` VARCHAR(255) NOT NULL,
 `Description` VARCHAR(255) NOT NULL,
 PRIMARY KEY (`POSExpTypeId`));

-- -----------------------------------------------------
-- Table `pb_db`.`CustomerDetails_SAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`CustomerDetails_SAL` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`CustomerDetails_SAL` (
 `CustomerId` VARCHAR(255) NOT NULL,
 `BusinessName` VARCHAR(255) NOT NULL,
 `Location` VARCHAR(255) NOT NULL,
 `EmailAddress` VARCHAR(255) NOT NULL,
 `Phonenumber` INT NOT NULL,
 `ContactName` VARCHAR(255) NOT NULL,
 PRIMARY KEY (`CustomerId`));
 
-- -----------------------------------------------------
-- Table `pb_db`.`ProductReceived_SAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`ProductReceived_SAL` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`ProductReceived_SAL` (
 `ProductReceiptId` INT NOT NULL AUTO_INCREMENT,
 `DispatchRefNum` INT NOT NULL,
 `Quantity` INT NOT NULL,
 `DateReceived` DATETIME NOT NULL,
 `Received` INT NOT NULL,
 `Comments` VARCHAR(255) NOT NULL,
 PRIMARY KEY (`ProductReceiptId`), 
 INDEX `DispatchRefNum_idx` (`DispatchRefNum` ASC), 
 CONSTRAINT `DispatchRefNum_PR`
 FOREIGN KEY (`DispatchRefNum`)
 REFERENCES `pb_db`.`DispatchProduct_ACC` (`DispatchRefNum`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT);

-- -----------------------------------------------------
-- Table `pb_db`.`SaleProductReceived_SAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`SaleProductReceived_SAL` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`SaleProductReceived_SAL` (
 `SalesRef` INT NOT NULL AUTO_INCREMENT,
 `ProductReceiptId` INT NOT NULL,
 `Quantity` INT NOT NULL,
 `UnitPrice` INT NOT NULL,
 `SalesDate` DATETIME NOT NULL,
 `PaymentMethod` VARCHAR(255) NOT NULL,
 `CustomerID` VARCHAR(255),
 PRIMARY KEY (`SalesRef`), 
 INDEX `ProductReceiptId_idx` (`ProductReceiptId` ASC), 
 INDEX `CustomerID_idx` (`CustomerID` ASC),
 CONSTRAINT `ProductReceiptId_SPR`
 FOREIGN KEY (`ProductReceiptId`)
 REFERENCES `pb_db`.`ProductReceived_SAL` (`ProductReceiptId`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT,
 CONSTRAINT `CustomerID_SPR`
 FOREIGN KEY (`CustomerID`)
 REFERENCES `pb_db`.`CustomerDetails_SAL` (`CustomerID`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT);

-- -----------------------------------------------------
-- Table `pb_db`.`POSExpDetails_SAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`POSExpDetails_SAL` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`POSExpDetails_SAL` (
 `POSExpDetailId` INT NOT NULL AUTO_INCREMENT,
 `ProductReceiptId` INT NOT NULL,
 `POSExpTypeId` INT NOT NULL,
 `Amount` INT NOT NULL,
 `ExpenditureDate` DATETIME NOT NULL,
 `Description` VARCHAR(255) NOT NULL,
 PRIMARY KEY (`POSExpDetailId`),
 INDEX `ProductReceiptId_idx` (`ProductReceiptId` ASC),
 INDEX `POSExpTypeId_idx` (`POSExpTypeId` ASC),
 CONSTRAINT `ProductReceiptId_PE`
 FOREIGN KEY (`ProductReceiptId`)
 REFERENCES `pb_db`.`ProductReceived_SAL` (`ProductReceiptId`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT,
 CONSTRAINT `POSExpTypeId_PE`
 FOREIGN KEY (`POSExpTypeId`)
 REFERENCES `pb_db`.`POSExpTypes_SAL` (`POSExpTypeId`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT);

-- -----------------------------------------------------
-- Table `pb_db`.`CollectPayment_SAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`CollectPayment_SAL` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`CollectPayment_SAL` (
 `PaymentRef` INT NOT NULL AUTO_INCREMENT,
 `SalesRef` INT NOT NULL,
 `Amount` INT NOT NULL,
 `PaymentMethod` VARCHAR(255) NOT NULL,
 `Attachment` BLOB,
 `Confirmation` INT NOT NULL,
 PRIMARY KEY (`PaymentRef`),
 INDEX `SalesRef_idx` (`SalesRef` ASC), 
 CONSTRAINT `SalesRef_CP`
 FOREIGN KEY (`SalesRef`)
 REFERENCES `pb_db`.`SaleProductReceived_SAL` (`SalesRef`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT);

-- -----------------------------------------------------
-- Table `pb_db`.`RegisterDeffectiveProd_SAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`RegisterDeffectiveProd_SAL` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`RegisterDeffectiveProd_SAL` (
 `DeffectiveRef` INT NOT NULL AUTO_INCREMENT,
 `ProductReceiptId` INT NOT NULL,
 `Quantity` INT NOT NULL,
 `Confirmation` INT NOT NULL,
 PRIMARY KEY (`DeffectiveRef`),
 INDEX `ProductReceiptId_idx` (`ProductReceiptId` ASC), 
 CONSTRAINT `ProductReceiptId_RDP`
 FOREIGN KEY (`ProductReceiptId`)
 REFERENCES `pb_db`.`ProductReceived_SAL` (`ProductReceiptId`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT);




-- -----------------------------------------------------
-- ADMIN MODULE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `pb_db`.`UserPermission_ADM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`UserPermission_ADM` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`UserPermission_ADM` (
 `PermissionID` INT NOT NULL AUTO_INCREMENT,
 `PermissionName` VARCHAR(255) NOT NULL,
 `Description` VARCHAR(255),
 PRIMARY KEY (`PermissionID`));

-- -----------------------------------------------------
-- Table `pb_db`.`UserRole_ADM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`UserRole_ADM` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`UserRole_ADM` (
 `RoleID` INT NOT NULL AUTO_INCREMENT,
 `RoleName` VARCHAR(255) NOT NULL,
 `RoleDescription` VARCHAR(255),
 `PermissionID` INT NOT NULL,
 PRIMARY KEY (`RoleID`),
 INDEX `PermissionID_idx` (`PermissionID` ASC), 
 CONSTRAINT `PermissionID_URS`
 FOREIGN KEY (`PermissionID`)
 REFERENCES `pb_db`.`UserPermission_ADM` (`PermissionID`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT);


-- -----------------------------------------------------
-- Table `pb_db`.`UserDetails_ADM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`UserDetails_ADM` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`UserDetails_ADM` (
 `UserDetailID` INT NOT NULL AUTO_INCREMENT,
 `EmployeeID` VARCHAR(255) NOT NULL,
 `RoleID` INT NOT NULL,
 `LoginName` VARCHAR(255) NOT NULL,
 `Password` VARCHAR(255) NOT NULL,
 PRIMARY KEY (`UserDetailID`),
 INDEX `EmployeeID_idx` (`EmployeeID` ASC), 
 INDEX `RoleID_idx` (`RoleID` ASC), 
 CONSTRAINT `RoleID_UD`
 FOREIGN KEY (`RoleID`)
 REFERENCES `pb_db`.`UserRole_ADM` (`RoleID`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT,
 CONSTRAINT `EmployeeID_UD`
 FOREIGN KEY (`EmployeeID`)
 REFERENCES `pb_db`.`PersonalInfo_HR` (`EmployeeID`)
 ON DELETE RESTRICT
 ON UPDATE RESTRICT);

-- -----------------------------------------------------
-- Table `pb_db`.`MOTD_ADM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`MOTD_ADM` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`MOTD_ADM` (
 `MessageID` INT NOT NULL AUTO_INCREMENT,
 `MessageDate` DATE NOT NULL,
 `Message` VARCHAR(255) NOT NULL,
 PRIMARY KEY (`MessageID`));











SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;