-- MySQL Script generated by MySQL RAJABU KITINDI
-- Nov 2019
-- Model: New Model Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pb_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pb_db` ;

-- -----------------------------------------------------
-- Schema pb_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pb_db` DEFAULT CHARACTER SET utf8 ;
USE `pb_db` ;



-- -----------------------------------------------------
-- HR MODULE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `pb_db`.`EmploymentType_HR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`EmploymentType_HR` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`EmploymentType_HR` (
 `EmpTypeId` INT NOT NULL AUTO_INCREMENT,
 `EmploymentType` VARCHAR(255) NOT NULL,
 `Description` VARCHAR(255),
 PRIMARY KEY (`EmpTypeId`));

-- -----------------------------------------------------
-- Table `pb_db`.`PaymentType_HR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`PaymentType_HR` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`PaymentType_HR` (
 `PayTypeId` INT NOT NULL AUTO_INCREMENT,
 `PaymentType` VARCHAR(255) NOT NULL,
 `Description` VARCHAR(255),
 PRIMARY KEY (`PayTypeId`));

-- -----------------------------------------------------
-- Table `pb_db`.`PaymentSchedule_HR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`PaymentSchedule_HR` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`PaymentSchedule_HR` (
 `PayScheduleId` INT NOT NULL AUTO_INCREMENT,
 `PaymentSchedule` VARCHAR(255) NOT NULL,
 `Description` VARCHAR(255),
 PRIMARY KEY (`PayScheduleId`));

-- -----------------------------------------------------
-- Table `pb_db`.`LeaveType_HR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`LeaveType_HR` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`LeaveType_HR` (
 `LeaveTypeId` INT NOT NULL AUTO_INCREMENT,
 `LeaveType` VARCHAR(255) NOT NULL,
 `PaymentStatus` VARCHAR(255) NOT NULL,
 `Description` VARCHAR(255),
 PRIMARY KEY (`LeaveTypeId`));
 
-- -----------------------------------------------------
-- Table `pb_db`.`Department_HR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`Department_HR` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`Department_HR` (
 `DepartmentId` INT NOT NULL AUTO_INCREMENT,
 `DepartmentName` VARCHAR(255) NOT NULL,
 `Description` VARCHAR(255),
 PRIMARY KEY (`DepartmentId`));

-- -----------------------------------------------------
-- Table `pb_db`.`PersonalInfo_HR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`PersonalInfo_HR` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`PersonalInfo_HR` (
 `EmployeeId` VARCHAR(255) NOT NULL,
 `FirstNames` VARCHAR(255) NOT NULL,
 `LastNames` VARCHAR(255) NOT NULL,
 `JoiningDate` DATE NOT NULL, 
 `Gender` VARCHAR(1) NOT NULL,
 `DateofBirth` DATE NOT NULL,
 `HomeAddress` VARCHAR(255) NOT NULL,
 `EmpIdPhoto` VARCHAR(255) NOT NULL,
 PRIMARY KEY (`EmployeeId`));

-- -----------------------------------------------------
-- Table `pb_db`.`EmergencyContact_HR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`EmergencyContact_HR`;

CREATE TABLE IF NOT EXISTS `pb_db`.`EmergencyContact_HR` (
 `eContactId` INT NOT NULL AUTO_INCREMENT,
 `EmployeeId` VARCHAR(255) NOT NULL,
 `FirstNames` VARCHAR(255) NOT NULL,
 `LastNames` VARCHAR(255) NOT NULL,
 `Email` VARCHAR(255), 
 `Phone` INT NOT NULL,
 `Address` VARCHAR(255) NOT NULL,
 `Relationship` VARCHAR(255) NOT NULL,
 `Other` VARCHAR(255),
 PRIMARY KEY (`eContactId`),
 INDEX `EmployeeId_idx` (`EmployeeId` ASC),
 CONSTRAINT `EmployeeId_EC`
 FOREIGN KEY (`EmployeeId`)
 REFERENCES `pb_db`.`PersonalInfo_HR` (`EmployeeId`)
 ON DELETE CASCADE
 ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `pb_db`.`EmploymentTypeInfo_HR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`EmploymentTypeInfo_HR`;

CREATE TABLE IF NOT EXISTS `pb_db`.`EmploymentTypeInfo_HR` (
 `EmpTypeInfoId` INT NOT NULL AUTO_INCREMENT,
 `EmployeeId` VARCHAR(255) NOT NULL,
 `EmpTypeId` INT NOT NULL,
 PRIMARY KEY (`EmpTypeInfoId`),
 INDEX `EmpTypeId_idx` (`EmpTypeId` ASC), 
 INDEX `EmployeeId_idx` (`EmployeeId` ASC),
 CONSTRAINT `EmpTypeId_ETI`
 FOREIGN KEY (`EmpTypeId`)
 REFERENCES `pb_db`.`EmploymentType_HR` (`EmpTypeId`)
 ON DELETE CASCADE
 ON UPDATE CASCADE,
 CONSTRAINT `EmployeeId_ETI`
 FOREIGN KEY (`EmployeeId`)
 REFERENCES `pb_db`.`PersonalInfo_HR` (`EmployeeId`)
 ON DELETE CASCADE
 ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `pb_db`.`EmployeeDeptInfo_HR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`EmployeeDeptInfo_HR`;

CREATE TABLE IF NOT EXISTS `pb_db`.`EmployeeDeptInfo_HR` (
 `EmpDeptInfoId` INT NOT NULL AUTO_INCREMENT,
 `EmployeeId` VARCHAR(255) NOT NULL,
 `DepartmentId` INT NOT NULL,
 `PositionTitle` VARCHAR(255),
 `RMID` VARCHAR(255),
 PRIMARY KEY (`EmpDeptInfoId`),
 INDEX `DepartmentId_idx` (`DepartmentId` ASC), 
 INDEX `EmployeeId_idx` (`EmployeeId` ASC),
 CONSTRAINT `DepartmentId_EDI`
 FOREIGN KEY (`DepartmentId`)
 REFERENCES `pb_db`.`Department_HR` (`DepartmentId`)
 ON DELETE CASCADE
 ON UPDATE CASCADE,
 CONSTRAINT `EmployeeId_EDI`
 FOREIGN KEY (`EmployeeId`)
 REFERENCES `pb_db`.`PersonalInfo_HR` (`EmployeeId`)
 ON DELETE CASCADE
 ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `pb_db`.`SalaryInfo_HR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`SalaryInfo_HR`;

CREATE TABLE IF NOT EXISTS `pb_db`.`SalaryInfo_HR` (
 `SalInfoId` INT NOT NULL AUTO_INCREMENT,
 `EmployeeId` VARCHAR(255) NOT NULL,
 `BaseSalary` INT NOT NULL,
 `StateTax` INT NOT NULL,
 `FederalTax` INT NOT NULL,
 `SocialSec` INT NOT NULL,
 `NetIncome` INT NOT NULL,
 `PayScheduleId` INT NOT NULL,
 PRIMARY KEY (`SalInfoId`), 
 INDEX `EmployeeId_idx` (`EmployeeId` ASC), 
 INDEX `PayScheduleId_idx` (`PayScheduleId` ASC),
 CONSTRAINT `EmployeeId_SI`
 FOREIGN KEY (`EmployeeId`)
 REFERENCES `pb_db`.`PersonalInfo_HR` (`EmployeeId`)
 ON DELETE CASCADE
 ON UPDATE CASCADE,
 CONSTRAINT `PayScheduleId`
 FOREIGN KEY (`PayScheduleId`)
 REFERENCES `pb_db`.`PaymentSchedule_HR` (`PayScheduleId`)
 ON DELETE CASCADE
 ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `pb_db`.`LeaveInfo_HR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`LeaveInfo_HR`;

CREATE TABLE IF NOT EXISTS `pb_db`.`LeaveInfo_HR` (
 `LeaveInfoId` INT NOT NULL AUTO_INCREMENT,
 `EmployeeId` VARCHAR(255) NOT NULL,
 `LeaveTypeId` INT NOT NULL,
 `NumberofDays` INT NOT NULL,
 `StartDate` DATETIME NOT NULL,
 `EndDate` DATETIME NOT NULL,
 PRIMARY KEY (`LeaveInfoId`), 
 INDEX `EmployeeId_idx` (`EmployeeId` ASC), 
 INDEX `LeaveTypeId_idx` (`LeaveTypeId` ASC),
 CONSTRAINT `EmployeeId_LI`
 FOREIGN KEY (`EmployeeId`)
 REFERENCES `pb_db`.`PersonalInfo_HR` (`EmployeeId`)
 ON DELETE CASCADE
 ON UPDATE CASCADE,
 CONSTRAINT `LeaveTypeId`
 FOREIGN KEY (`LeaveTypeId`)
 REFERENCES `pb_db`.`LeaveType_HR` (`LeaveTypeId`)
 ON DELETE CASCADE
 ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `pb_db`.`BankInfo_HR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`BankInfo_HR` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`BankInfo_HR` (
 `BankInfoId` INT NOT NULL AUTO_INCREMENT,
 `EmployeeId` VARCHAR(255) NOT NULL,
 `BankName` VARCHAR(255) NOT NULL,
 `BankCode` VARCHAR(255) NOT NULL,
 `BranchCodeNumber` VARCHAR(255) NOT NULL,
 `AccountNumber` INT NOT NULL,
 `CLABE` INT NOT NULL,
 `AccountType` VARCHAR(255) NOT NULL,
 PRIMARY KEY (`BankInfoId`), 
 INDEX `EmployeeId_idx` (`EmployeeId` ASC), 
 CONSTRAINT `EmployeeId_BI`
 FOREIGN KEY (`EmployeeId`)
 REFERENCES `pb_db`.`PersonalInfo_HR` (`EmployeeId`)
 ON DELETE CASCADE
 ON UPDATE CASCADE);



-- -----------------------------------------------------
-- PRODUCTION MODULE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `pb_db`.`SupplierCategory_PROD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`SupplierCategory_PROD` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`SupplierCategory_PROD` (
 `CategoryId` INT NOT NULL,
 `CategoryName` VARCHAR(255) NOT NULL,
 `Description` VARCHAR(255),
 PRIMARY KEY (`CategoryId`));
 
-- -----------------------------------------------------
-- Table `pb_db`.`ExpenseType_PROD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`ExpenseType_PROD` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`ExpenseType_PROD` (
 `ExpTypeId` INT NOT NULL AUTO_INCREMENT,
 `ExpenseType` VARCHAR(255) NOT NULL,
 `Description` VARCHAR(255),
 PRIMARY KEY (`ExpTypeId`));
 
-- -----------------------------------------------------
-- Table `pb_db`.`ProductQuality_PROD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`ProductQuality_PROD` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`ProductQuality_PROD` (
 `QualityId` INT NOT NULL AUTO_INCREMENT,
 `QualityName` VARCHAR(255) NOT NULL,
 `Description` VARCHAR(255),
 PRIMARY KEY (`QualityId`));
 
-- -----------------------------------------------------
-- Table `pb_db`.`ProductBrand_PROD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`ProductBrand_PROD` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`ProductBrand_PROD` (
 `BrandId` INT NOT NULL AUTO_INCREMENT,
 `BrandName` VARCHAR(255) NOT NULL,
 `Description` VARCHAR(255),
 PRIMARY KEY (`BrandId`));

-- -----------------------------------------------------
-- Table `pb_db`.`SupplierInfo_PROD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`SupplierInfo_PROD` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`SupplierInfo_PROD` (
 `SupplierId` VARCHAR(255) NOT NULL,
 `BusinessName` VARCHAR(255) NOT NULL,
 `ContactName` VARCHAR(255) NOT NULL,
 `Address` VARCHAR(255) NOT NULL,
 `EmailAddress` VARCHAR(255) NOT NULL,
 `PhoneNumber` INT NOT NULL,
 `CategoryId` INT NOT NULL,
 PRIMARY KEY (`SupplierId`), 
 INDEX `CategoryId_idx` (`CategoryId` ASC), 
 CONSTRAINT `CategoryId`
 FOREIGN KEY (`CategoryId`)
 REFERENCES `pb_db`.`SupplierCategory_PROD` (`CategoryId`)
 ON DELETE CASCADE
 ON UPDATE CASCADE);
 
 -- -----------------------------------------------------
-- Table `pb_db`.`FarmInfo_PROD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`FarmInfo_PROD` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`FarmInfo_PROD` (
 `FarmId` INT NOT NULL AUTO_INCREMENT,
 `FarmName` VARCHAR(255) NOT NULL,
 `FarmSize` INT NOT NULL,
 `SupplierId` VARCHAR(255) NOT NULL,
 PRIMARY KEY (`FarmId`), 
 INDEX `SupplierId_idx` (`SupplierId` ASC), 
 CONSTRAINT `SupplierId_FI`
 FOREIGN KEY (`SupplierId`)
 REFERENCES `pb_db`.`SupplierInfo_PROD` (`SupplierId`)
 ON DELETE CASCADE
 ON UPDATE CASCADE);
 
 -- -----------------------------------------------------
-- Table `pb_db`.`TruckInfo_PROD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`TruckInfo_PROD` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`TruckInfo_PROD` (
 `RegNumber` VARCHAR(255) NOT NULL,
 `Make` VARCHAR(255) NOT NULL,
 `Model` VARCHAR(255) NOT NULL,
 `Capacity` VARCHAR(255) NOT NULL,
 `DriverName` VARCHAR(255) NOT NULL,
 `SupplierId` VARCHAR(255) NOT NULL,
 PRIMARY KEY (`RegNumber`), 
 INDEX `SupplierId_idx` (`SupplierId` ASC), 
 CONSTRAINT `SupplierId_TI`
 FOREIGN KEY (`SupplierId`)
 REFERENCES `pb_db`.`SupplierInfo_PROD` (`SupplierId`)
 ON DELETE CASCADE
 ON UPDATE CASCADE);
 
-- -----------------------------------------------------
-- Table `pb_db`.`ProductInfo_PROD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`ProductInfo_PROD` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`ProductInfo_PROD` (
 `ProductCode` VARCHAR(255) NOT NULL,
 `BrandId` INT NOT NULL,
 `QualityId` INT NOT NULL,
 `ProductPhoto` VARCHAR(255) NULL,
 `SellingPrice` INT NOT NULL,
 `SupplierId` VARCHAR(255) NOT NULL,
 PRIMARY KEY (`ProductCode`), 
 INDEX `SupplierId_idx` (`SupplierId` ASC), 
 INDEX `BrandId_idx` (`BrandId` ASC),
 INDEX `QualityId_idx` (`QualityId` ASC),
 CONSTRAINT `SupplierId_PI`
 FOREIGN KEY (`SupplierId`)
 REFERENCES `pb_db`.`SupplierInfo_PROD` (`SupplierId`)
 ON DELETE CASCADE
 ON UPDATE CASCADE,
 CONSTRAINT `BrandId_PI`
 FOREIGN KEY (`BrandId`)
 REFERENCES `pb_db`.`ProductBrand_PROD` (`BrandId`)
 ON DELETE CASCADE
 ON UPDATE CASCADE,
 CONSTRAINT `QualityId_PI`
 FOREIGN KEY (`QualityId`)
 REFERENCES `pb_db`.`ProductQuality_PROD` (`QualityId`)
 ON DELETE CASCADE
 ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `pb_db`.`CaseDetails_PROD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`CaseDetails_PROD` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`CaseDetails_PROD` (
 `CaseCode` VARCHAR(255) NOT NULL,
 `CaseName` VARCHAR(255) NOT NULL,
 `BrandId` INT NOT NULL,
 `CasePhoto` VARCHAR(255) NULL,
 `PurchasePrice` INT NOT NULL,
 `SupplierId` VARCHAR(255) NOT NULL,
 PRIMARY KEY (`CaseCode`), 
 INDEX `BrandId_idx` (`BrandId` ASC),
 INDEX `SupplierId_idx` (`SupplierId` ASC), 
 CONSTRAINT `SupplierId_CD`
 FOREIGN KEY (`SupplierId`)
 REFERENCES `pb_db`.`SupplierInfo_PROD` (`SupplierId`)
 ON DELETE CASCADE
 ON UPDATE CASCADE,
 CONSTRAINT `BrandId_CD`
 FOREIGN KEY (`BrandId`)
 REFERENCES `pb_db`.`ProductBrand_PROD` (`BrandId`)
 ON DELETE CASCADE
 ON UPDATE CASCADE);




-- -----------------------------------------------------
-- SALES MODULE
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Table `pb_db`.`POSInfo_SAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`POSInfo_SAL` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`POSInfo_SAL` (
 `POSId` INT NOT NULL,
 `POSName` VARCHAR(255) NOT NULL,
 `EmployeeID` VARCHAR(255),
 PRIMARY KEY (`POSId`),
 INDEX `EmployeeID_idx` (`EmployeeID` ASC), 
 CONSTRAINT `EmployeeID_POSI`
 FOREIGN KEY (`EmployeeID`)
 REFERENCES `pb_db`.`PersonalInfo_HR` (`EmployeeID`)
 ON DELETE CASCADE
 ON UPDATE CASCADE);




-- -----------------------------------------------------
-- ACCOUNTING MODULE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `pb_db`.`BatchRange_ACC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`BatchRange_ACC` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`BatchRange_ACC` (
 `BatchRangeId` VARCHAR(255) NOT NULL,
 `StartingNumber` INT NOT NULL,
 `EndingNumber` INT NOT NULL,
 `SFIndication` VARCHAR(1) NOT NULL,
 `Description` VARCHAR(255),
 PRIMARY KEY (`BatchRangeId`));

-- -----------------------------------------------------
-- Table `pb_db`.`BatchDetails_ACC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`BatchDetails_ACC` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`BatchDetails_ACC` (
 `BatchId` INT NOT NULL AUTO_INCREMENT,
 `ControlNumber` INT NOT NULL,
 `BatchRangeId` VARCHAR(255) NOT NULL,
 `SupplierId` VARCHAR(255) NOT NULL,
 `RegNumber` VARCHAR(255) NOT NULL,
 `DateDispatched` DATE NOT NULL,
 `DateArrived` DATE NOT NULL,
 `BatchDocument` VARCHAR(255) NOT NULL,
 `RangeCycle` INT NOT NULL,
 `ProductCount` INT NOT NULL,
 PRIMARY KEY (`BatchId`), 
 INDEX `SupplierId_idx` (`SupplierId` ASC), 
 INDEX `RegNumber_idx` (`RegNumber` ASC),
 INDEX `BatchRangeId_idx` (`BatchRangeId` ASC),
 CONSTRAINT `SupplierId_BD`
 FOREIGN KEY (`SupplierId`)
 REFERENCES `pb_db`.`SupplierInfo_PROD` (`SupplierId`)
 ON DELETE CASCADE
 ON UPDATE CASCADE,
 CONSTRAINT `RegNumber_BD`
 FOREIGN KEY (`RegNumber`)
 REFERENCES `pb_db`.`TruckInfo_PROD` (`RegNumber`)
 ON DELETE CASCADE
 ON UPDATE CASCADE,
 CONSTRAINT `BatchRangeId_BD`
 FOREIGN KEY (`BatchRangeId`)
 REFERENCES `pb_db`.`BatchRange_ACC` (`BatchRangeId`)
 ON DELETE CASCADE
 ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `pb_db`.`ReceiveProduct_ACC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`ReceiveProduct_ACC` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`ReceiveProduct_ACC` (
 `ProductReceiptNumber` INT NOT NULL AUTO_INCREMENT,
 `ProductCode` VARCHAR(255) NOT NULL,
 `BatchId` INT NOT NULL,  
 `FarmId` INT NOT NULL,
 `Quantity` INT NOT NULL,
 `CaseCode` VARCHAR(255) NOT NULL,
 `DateReceived` DATE NOT NULL,
 PRIMARY KEY (`ProductReceiptNumber`), 
 INDEX `ProductCode_idx` (`ProductCode` ASC), 
 INDEX `BatchId_idx` (`BatchId` ASC),
 INDEX `FarmId_idx` (`FarmId` ASC),
 INDEX `CaseCode_idx` (`CaseCode` ASC),
 CONSTRAINT `ProductCode_RP`
 FOREIGN KEY (`ProductCode`)
 REFERENCES `pb_db`.`ProductInfo_PROD` (`ProductCode`)
 ON DELETE CASCADE
 ON UPDATE CASCADE,
 CONSTRAINT `BatchId_RP`
 FOREIGN KEY (`BatchId`)
 REFERENCES `pb_db`.`BatchDetails_ACC` (`BatchId`)
 ON DELETE CASCADE
 ON UPDATE CASCADE,
 CONSTRAINT `FarmId_RP`
 FOREIGN KEY (`FarmId`)
 REFERENCES `pb_db`.`FarmInfo_PROD` (`FarmId`)
 ON DELETE CASCADE
 ON UPDATE CASCADE,
 CONSTRAINT `CaseCode_RP`
 FOREIGN KEY (`CaseCode`)
 REFERENCES `pb_db`.`CaseDetails_PROD` (`CaseCode`)
 ON DELETE CASCADE
 ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `pb_db`.`DispatchProduct_ACC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`DispatchProduct_ACC` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`DispatchProduct_ACC` (
 `DispatchRefNum` INT NOT NULL AUTO_INCREMENT,
 `ProductReceiptNumber` INT NOT NULL,
 `POSId` INT NOT NULL,
 `Quantity` INT NOT NULL,
 `DateDispatched` DATETIME NOT NULL,
 `Dispatched` VARCHAR(1) NOT NULL,
 `Comments` VARCHAR(255),
 PRIMARY KEY (`DispatchRefNum`), 
 INDEX `ProductReceiptNumber_idx` (`ProductReceiptNumber` ASC), 
 INDEX `POSId_idx` (`POSId` ASC),
 CONSTRAINT `ProductReceiptNumber_DP`
 FOREIGN KEY (`ProductReceiptNumber`)
 REFERENCES `pb_db`.`ReceiveProduct_ACC` (`ProductReceiptNumber`)
 ON DELETE CASCADE
 ON UPDATE CASCADE,
 CONSTRAINT `POSId_DP`
 FOREIGN KEY (`POSId`)
 REFERENCES `pb_db`.`POSInfo_SAL` (`POSId`)
 ON DELETE CASCADE
 ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `pb_db`.`BatchExp_ACC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`BatchExp_ACC` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`BatchExp_ACC` (
 `BatchExpId` INT NOT NULL AUTO_INCREMENT,
 `BatchId` INT NOT NULL,
 `FreighCost` INT NOT NULL,
 `iva` INT NOT NULL,
 `retiva` INT NOT NULL,
 PRIMARY KEY (`BatchExpId`),
 INDEX `BatchId_idx` (`BatchId` ASC), 
 CONSTRAINT `BatchId_BC`
 FOREIGN KEY (`BatchId`)
 REFERENCES `pb_db`.`BatchDetails_ACC` (`BatchId`)
 ON DELETE CASCADE
 ON UPDATE CASCADE);
 
 
 
 
-- -----------------------------------------------------
-- SALES MODULE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `pb_db`.`POSExpTypes_SAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`POSExpTypes_SAL` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`POSExpTypes_SAL` (
 `POSExpTypeId` INT NOT NULL AUTO_INCREMENT,
 `POSExpType` VARCHAR(255) NOT NULL,
 `Description` VARCHAR(255) NOT NULL,
 PRIMARY KEY (`POSExpTypeId`));

-- -----------------------------------------------------
-- Table `pb_db`.`CustomerDetails_SAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`CustomerDetails_SAL` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`CustomerDetails_SAL` (
 `CustomerId` VARCHAR(255) NOT NULL,
 `BusinessName` VARCHAR(255) NOT NULL,
 `Location` VARCHAR(255) NOT NULL,
 `EmailAddress` VARCHAR(255) NOT NULL,
 `Phonenumber` INT NOT NULL,
 `ContactName` VARCHAR(255) NOT NULL,
 PRIMARY KEY (`CustomerId`));
 
-- -----------------------------------------------------
-- Table `pb_db`.`ProductReceived_SAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`ProductReceived_SAL` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`ProductReceived_SAL` (
 `ProductReceiptId` INT NOT NULL AUTO_INCREMENT,
 `DispatchRefNum` INT NOT NULL,
 `Quantity` INT NOT NULL,
 `DateReceived` DATETIME NOT NULL,
 `Received` VARCHAR(1) NOT NULL,
 `Comments` VARCHAR(255) NOT NULL,
 PRIMARY KEY (`ProductReceiptId`), 
 INDEX `DispatchRefNum_idx` (`DispatchRefNum` ASC), 
 CONSTRAINT `DispatchRefNum_PR`
 FOREIGN KEY (`DispatchRefNum`)
 REFERENCES `pb_db`.`DispatchProduct_ACC` (`DispatchRefNum`)
 ON DELETE CASCADE
 ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `pb_db`.`SaleProductReceived_SAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`SaleProductReceived_SAL` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`SaleProductReceived_SAL` (
 `SalesRef` INT NOT NULL AUTO_INCREMENT,
 `ProductReceiptId` INT NOT NULL,
 `Quantity` INT NOT NULL,
 `UnitPrice` INT NOT NULL,
 `SalesDate` DATETIME NOT NULL,
 `PaymentMethod` VARCHAR(255) NOT NULL,
 `CustomerID` VARCHAR(255),
 `RecordInsertDate` DATETIME NOT NULL,
 PRIMARY KEY (`SalesRef`), 
 INDEX `ProductReceiptId_idx` (`ProductReceiptId` ASC), 
 INDEX `CustomerID_idx` (`CustomerID` ASC),
 CONSTRAINT `ProductReceiptId_SPR`
 FOREIGN KEY (`ProductReceiptId`)
 REFERENCES `pb_db`.`ProductReceived_SAL` (`ProductReceiptId`)
 ON DELETE CASCADE
 ON UPDATE CASCADE,
 CONSTRAINT `CustomerID_SPR`
 FOREIGN KEY (`CustomerID`)
 REFERENCES `pb_db`.`CustomerDetails_SAL` (`CustomerID`)
 ON DELETE CASCADE
 ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `pb_db`.`POSExpDetails_SAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`POSExpDetails_SAL` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`POSExpDetails_SAL` (
 `POSExpDetailId` INT NOT NULL AUTO_INCREMENT,
 `ProductReceiptId` INT NOT NULL,
 `POSExpTypeId` INT NOT NULL,
 `Amount` INT NOT NULL,
 `ExpenditureDate` DATETIME NOT NULL,
 `Description` VARCHAR(255) NOT NULL,
 PRIMARY KEY (`POSExpDetailId`),
 INDEX `ProductReceiptId_idx` (`ProductReceiptId` ASC),
 INDEX `POSExpTypeId_idx` (`POSExpTypeId` ASC),
 CONSTRAINT `ProductReceiptId_PE`
 FOREIGN KEY (`ProductReceiptId`)
 REFERENCES `pb_db`.`ProductReceived_SAL` (`ProductReceiptId`)
 ON DELETE CASCADE
 ON UPDATE CASCADE,
 CONSTRAINT `POSExpTypeId_PE`
 FOREIGN KEY (`POSExpTypeId`)
 REFERENCES `pb_db`.`POSExpTypes_SAL` (`POSExpTypeId`)
 ON DELETE CASCADE
 ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `pb_db`.`CollectPayment_SAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`CollectPayment_SAL` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`CollectPayment_SAL` (
 `PaymentRef` INT NOT NULL AUTO_INCREMENT,
 `SalesRef` INT NOT NULL,
 `Amount` INT NOT NULL,
 `PaymentMethod` VARCHAR(255) NOT NULL,
 `PaymentDate` DATETIME NOT NULL,
 `Attachment` VARCHAR(255),
 `Confirmation` VARCHAR(1) NOT NULL,
 `Comments` VARCHAR(255),
 PRIMARY KEY (`PaymentRef`),
 INDEX `SalesRef_idx` (`SalesRef` ASC), 
 CONSTRAINT `SalesRef_CP`
 FOREIGN KEY (`SalesRef`)
 REFERENCES `pb_db`.`SaleProductReceived_SAL` (`SalesRef`)
 ON DELETE CASCADE
 ON UPDATE CASCADE);

-- --------------------------------------------------------------
-- Table `pb_db`.`RegisterDeffectiveProd_SAL`
-- --------------------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`RegisterDeffectiveProd_SAL`;

CREATE TABLE IF NOT EXISTS `pb_db`.`RegisterDeffectiveProd_SAL`(
 `DeffectiveRef` INT NOT NULL AUTO_INCREMENT,
 `ProductReceiptId` INT NOT NULL,
 `Quantity` INT NOT NULL,
 `Confirmation` VARCHAR(1) NOT NULL,
 `DateReported` DATETIME NOT NULL,
 `Comments` VARCHAR(255) NOT NULL,
 PRIMARY KEY (`DeffectiveRef`),
 INDEX `ProductReceiptId_idx` (`ProductReceiptId` ASC), 
 CONSTRAINT `ProductReceiptId_RDP`
 FOREIGN KEY (`ProductReceiptId`)
 REFERENCES `pb_db`.`ProductReceived_SAL` (`ProductReceiptId`)
 ON DELETE CASCADE
 ON UPDATE CASCADE);




-- -------------------------------------------------------------
-- ADMIN MODULE
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- Table `pb_db`.`UserPermission_ADM`
-- -------------------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`UserPermission_ADM` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`UserPermission_ADM` (
 `PermissionID` INT NOT NULL AUTO_INCREMENT,
 `PermissionName` VARCHAR(255) NOT NULL,
 `Description` VARCHAR(255),
 PRIMARY KEY (`PermissionID`));

-- -----------------------------------------------------
-- Table `pb_db`.`UserRole_ADM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`UserRole_ADM` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`UserRole_ADM` (
 `RoleID` INT NOT NULL AUTO_INCREMENT,
 `RoleName` VARCHAR(255) NOT NULL,
 `RoleDescription` VARCHAR(255),
 PRIMARY KEY (`RoleID`));
 
-- -----------------------------------------------------
-- Table `pb_db`.`Role_Perm_ADM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`Role_Perm_ADM`;

CREATE TABLE IF NOT EXISTS `pb_db`.`Role_Perm_ADM` (
 `ID` INT NOT NULL AUTO_INCREMENT,
 `RoleName` VARCHAR(255) NOT NULL,
 `PermissionName` VARCHAR(255),
 PRIMARY KEY (`ID`));

-- -----------------------------------------------------
-- Table `pb_db`.`UserDetails_ADM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`UserDetails_ADM` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`UserDetails_ADM` (
 `UserDetailID` INT NOT NULL AUTO_INCREMENT,
 `EmployeeID` VARCHAR(255) NOT NULL,
 `RoleID` INT NOT NULL,
 `LoginName` VARCHAR(255) NOT NULL,
 `Password` VARCHAR(255) NOT NULL,
 PRIMARY KEY (`UserDetailID`),
 INDEX `EmployeeID_idx` (`EmployeeID` ASC), 
 INDEX `RoleID_idx` (`RoleID` ASC), 
 CONSTRAINT `RoleID_UD`
 FOREIGN KEY (`RoleID`)
 REFERENCES `pb_db`.`UserRole_ADM` (`RoleID`)
 ON DELETE CASCADE
 ON UPDATE CASCADE,
 CONSTRAINT `EmployeeID_UD`
 FOREIGN KEY (`EmployeeID`)
 REFERENCES `pb_db`.`PersonalInfo_HR` (`EmployeeID`)
 ON DELETE CASCADE
 ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `pb_db`.`MOTD_ADM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`MOTD_ADM` ;

CREATE TABLE IF NOT EXISTS `pb_db`.`MOTD_ADM` (
 `MessageID` INT NOT NULL AUTO_INCREMENT,
 `MessageDate` DATE NOT NULL,
 `Message` VARCHAR(255) NOT NULL,
 PRIMARY KEY (`MessageID`));


-- -----------------------------------------------------
-- Table `pb_db`.`REPORTPROBLEMS_ADM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`REPORTPROBLEMS_ADM`;

CREATE TABLE IF NOT EXISTS `pb_db`.`REPORTPROBLEMS_ADM`(
 `ProblemID` INT NOT NULL AUTO_INCREMENT,
 `EmployeeID` VARCHAR(255) NOT NULL,
 `ProblemDesc` VARCHAR(255) NOT NULL,
 `DateOccured` DATE NOT NULL,
 PRIMARY KEY (`ProblemID`),
 INDEX `EmployeeID_idx` (`EmployeeID` ASC),
 CONSTRAINT `EmployeeID_RPA`
 FOREIGN KEY (`EmployeeID`)
 REFERENCES `pb_db`.`PersonalInfo_HR` (`EmployeeID`)
 ON DELETE CASCADE
 ON UPDATE CASCADE);




-- -----------------------------------------------------
-- AUDIT TRAIL MODULE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `pb_db`.`LOGIN_TBL_AT`, REPORT LOGIN DATE & TIME
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`LOGIN_TBL_ADM`;

CREATE TABLE IF NOT EXISTS `pb_db`.`LOGIN_TBL_ADM` (
 `TransactionID` INT NOT NULL AUTO_INCREMENT,
 `EmployeeID` VARCHAR(255) NOT NULL,
 `LoginDate` DATETIME NOT NULL,
 PRIMARY KEY (`TransactionID`),
 INDEX `EmployeeID_idx` (`EmployeeID` ASC), 
 CONSTRAINT `EmployeeID_LT`
 FOREIGN KEY (`EmployeeID`)
 REFERENCES `pb_db`.`PersonalInfo_HR` (`EmployeeID`)
 ON DELETE CASCADE
 ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `pb_db`.`LOGOUT_TBL_AT`, REPORT LOGOUT DATE & TIME
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`LOGOUT_TBL_AT`;

CREATE TABLE IF NOT EXISTS `pb_db`.`LOGOUT_TBL_AT` (
 `TransactionID` INT NOT NULL AUTO_INCREMENT,
 `EmployeeID` VARCHAR(255) NOT NULL,
 `LogoutDate` DATETIME NOT NULL,
 PRIMARY KEY (`TransactionID`),
 INDEX `EmployeeID_idx` (`EmployeeID` ASC), 
 CONSTRAINT `EmployeeID_LTA`
 FOREIGN KEY (`EmployeeID`)
 REFERENCES `pb_db`.`PersonalInfo_HR` (`EmployeeID`)
 ON DELETE CASCADE
 ON UPDATE CASCADE);
 
-- -----------------------------------------------------
-- Table `pb_db`.`ACTION_TBL_AT`, REPORT ACTION TAKEN ON A FORM
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pb_db`.`ACTION_TBL_AT`;

CREATE TABLE IF NOT EXISTS `pb_db`.`ACTION_TBL_AT` (
 `TransactionID` INT NOT NULL AUTO_INCREMENT,
 `EmployeeID` VARCHAR(255) NOT NULL,
 `FormName` VARCHAR(255) NOT NULL,
 `ActionTaken` VARCHAR(255) NOT NULL,
 `AccessDate` DATETIME NOT NULL,
 PRIMARY KEY (`TransactionID`),
 INDEX `EmployeeID_idx` (`EmployeeID` ASC), 
 CONSTRAINT `EmployeeID_ATA`
 FOREIGN KEY (`EmployeeID`)
 REFERENCES `pb_db`.`PersonalInfo_HR` (`EmployeeID`)
 ON DELETE CASCADE
 ON UPDATE CASCADE);






SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;